#!/usr/bin/env bash
#
# install.sh — first-run installer for the Intelligent ERP stack on a fresh PC.
#
# One command sets up everything the website needs: it checks the tools it
# depends on, generates secrets, builds and starts every service in Docker,
# runs the database migrations, downloads the local AI model, seeds demo data,
# and health-checks each endpoint. It is idempotent — safe to re-run.
#
# The ONLY thing you must install yourself first is Docker Desktop (Windows /
# macOS) or Docker Engine + the compose plugin (Linux). Everything else —
# PHP, Node, PostgreSQL, the AI model — runs inside Docker and is handled here.
#
# Usage:
#   ./install.sh            # full setup, then start everything
#   ./install.sh --rebuild  # force a clean, no-cache rebuild of all images
#   ./install.sh --down     # stop and remove the stack (keeps your data)
#
set -euo pipefail
cd "$(dirname "$0")"

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()   { printf '   \033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '   \033[1;33m!\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

REBUILD=0
for arg in "${@:-}"; do
  case "$arg" in
    --rebuild) REBUILD=1 ;;
    --down)    docker compose down; echo "Stack stopped (data volumes kept)."; exit 0 ;;
    "")        ;;
    *) die "Unknown option: $arg  (use --rebuild or --down)" ;;
  esac
done

# ---------------------------------------------------------------------------
# 1. prerequisites
# ---------------------------------------------------------------------------
log "Checking prerequisites"

command -v docker >/dev/null 2>&1 || die \
"Docker is not installed.
   Install Docker Desktop (Windows/macOS) from https://www.docker.com/products/docker-desktop
   or Docker Engine + compose plugin (Linux), then run ./install.sh again."

if ! docker compose version >/dev/null 2>&1; then
  die "The Docker Compose plugin is missing. Update Docker Desktop, or install docker-compose-plugin (Linux)."
fi
ok "Docker and Docker Compose are installed"

docker info >/dev/null 2>&1 || die \
"The Docker daemon is not running. Start Docker Desktop (or 'sudo systemctl start docker'), then re-run."
ok "Docker daemon is running"

command -v openssl >/dev/null 2>&1 || die "openssl is required to generate secrets. Install it and re-run."
command -v curl    >/dev/null 2>&1 || warn "curl not found — the health checks at the end will be skipped."

# ---------------------------------------------------------------------------
# 2. GPU detection — the AI model runs on GPU if available, else CPU
# ---------------------------------------------------------------------------
# The base compose file reserves an NVIDIA GPU for the Ollama service. On a
# machine without one that would fail to start, so when no NVIDIA GPU is found
# we layer a small override that runs Ollama on the CPU instead (slower, but it
# works everywhere).
log "Detecting GPU"
DC=(docker compose)
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
  ok "NVIDIA GPU detected — the AI model will use it"
else
  warn "No NVIDIA GPU detected — the AI model will run on CPU (slower but fully functional)"
  cat > docker-compose.cpu.yml <<'YAML'
# Auto-generated by install.sh on machines without an NVIDIA GPU.
# Drops the GPU reservation so the Ollama service starts on CPU.
services:
  ollama:
    deploy:
      resources:
        reservations:
          devices: []
YAML
  DC=(docker compose -f docker-compose.yml -f docker-compose.cpu.yml)
fi

# ---------------------------------------------------------------------------
# 3. .env with generated secrets (only if missing)
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  log "Creating .env with generated secrets"
  APP_KEY="base64:$(openssl rand -base64 32)"
  JWT_SECRET="$(openssl rand -hex 32)"
  DB_PW="erp_$(openssl rand -hex 8)"
  sed -e "s|^APP_KEY=.*|APP_KEY=${APP_KEY}|" \
      -e "s|^JWT_SECRET=.*|JWT_SECRET=${JWT_SECRET}|" \
      -e "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${DB_PW}|" \
      -e "s|^DB_PASSWORD=.*|DB_PASSWORD=${DB_PW}|" \
      .env.example > .env
  ok ".env created with fresh secrets"
else
  ok ".env already exists — leaving it untouched"
fi

# Read the model name from .env so we pull whatever the app is configured for.
OLLAMA_MODEL="$(grep -E '^OLLAMA_MODEL=' .env | cut -d= -f2- | tr -d '\042\047[:space:]')"
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen3:14b}"

# ---------------------------------------------------------------------------
# 4. build images
# ---------------------------------------------------------------------------
if [ "$REBUILD" -eq 1 ]; then
  log "Rebuilding all images (no cache) — this can take several minutes"
  "${DC[@]}" build --no-cache
else
  log "Building images — first run downloads base images and can take several minutes"
  "${DC[@]}" build
fi
ok "Images built"

# ---------------------------------------------------------------------------
# 5. backend PHP dependencies (bind-mounted, so vendor/ must exist on the host)
# ---------------------------------------------------------------------------
if [ ! -f backend/vendor/autoload.php ]; then
  log "Installing backend dependencies (Composer)"
  "${DC[@]}" run --rm --no-deps -T backend composer install --no-interaction --prefer-dist
  ok "Backend dependencies installed"
else
  ok "Backend dependencies already present"
fi

# ---------------------------------------------------------------------------
# 6. start the stack
# ---------------------------------------------------------------------------
log "Starting all services"
"${DC[@]}" up -d
ok "Containers started"

# ---------------------------------------------------------------------------
# 7. wait for the database, run migrations
# ---------------------------------------------------------------------------
log "Waiting for the database to be ready"
for _ in $(seq 1 60); do
  [ "$("${DC[@]}" ps db --format '{{.Health}}' 2>/dev/null)" = "healthy" ] && break
  sleep 2
done
[ "$("${DC[@]}" ps db --format '{{.Health}}' 2>/dev/null)" = "healthy" ] || die "Database did not become healthy in time. Check: ${DC[*]} logs db"
ok "Database is ready"

log "Running database migrations"
"${DC[@]}" exec -T backend php artisan migrate --force
ok "Migrations applied"

# ---------------------------------------------------------------------------
# 8. download the local AI model (large — first run only)
# ---------------------------------------------------------------------------
log "Waiting for the AI engine (Ollama) to accept connections"
for _ in $(seq 1 60); do
  "${DC[@]}" exec -T ollama ollama list >/dev/null 2>&1 && break
  sleep 2
done

if "${DC[@]}" exec -T ollama ollama list 2>/dev/null | grep -q "${OLLAMA_MODEL%%:*}"; then
  ok "AI model '${OLLAMA_MODEL}' already downloaded"
else
  log "Downloading the AI model '${OLLAMA_MODEL}' — this is several GB and can take a while"
  "${DC[@]}" exec -T ollama ollama pull "${OLLAMA_MODEL}" \
    && ok "AI model ready" \
    || warn "Could not pull '${OLLAMA_MODEL}' now. The assistant will pull it on first use, or run: ${DC[*]} exec ollama ollama pull ${OLLAMA_MODEL}"
fi

# ---------------------------------------------------------------------------
# 9. seed demo data (first run only)
# ---------------------------------------------------------------------------
if [ ! -f .seeded ]; then
  log "Seeding demo data (products, customers, demo accounts)"
  "${DC[@]}" exec -T backend php artisan db:seed --class=DemoSeeder --force
  # Fill every module with a realistic dataset by driving the app's own API
  # (needs the backend serving, which it is by now). Best-effort.
  log "Populating every module with demo data"
  "${DC[@]}" exec -T backend php artisan erp:seed-showcase \
    && ok "Every module populated" \
    || warn "Could not populate showcase data; run later: ${DC[*]} exec backend php artisan erp:seed-showcase"
  touch .seeded
  ok "Demo data seeded"
else
  ok "Demo data already seeded"
fi

# ---------------------------------------------------------------------------
# 10. health checks
# ---------------------------------------------------------------------------
if command -v curl >/dev/null 2>&1; then
  log "Health checks"
  check() { printf '   %-12s %-34s -> HTTP %s\n' "$1" "$2" "$(curl -s -o /dev/null -w '%{http_code}' "$2" || echo 000)"; }
  check "frontend"   http://localhost:5173
  check "backend"    http://localhost:8000
  check "ai-service" http://localhost:8001/ready
fi

cat <<EOF

────────────────────────────────────────────────────────
 Setup complete. Open the app:  http://localhost:5173
────────────────────────────────────────────────────────

 Demo logins:
   superadmin@erp.local  / Super123!    (full control + roles)
   admin@erp.local       / Admin123!
   manager@erp.local     / Manager123!
   employee@erp.local    / Employee123!

 Handy commands:
   ${DC[*]} ps
   ${DC[*]} logs -f backend
   ./install.sh --down          # stop everything (keeps your data)
   ./install.sh --rebuild       # clean rebuild of all images

EOF
