<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: DejaVu Sans, sans-serif; color: #1e293b; font-size: 12px; }
    h1 { font-size: 26px; color: #4f46e5; margin: 0; }
    .meta { text-align: right; color: #475569; }
    .parties { margin: 24px 0; }
    .label { font-size: 10px; text-transform: uppercase; color: #94a3b8; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th { text-align: left; background: #f1f5f9; padding: 8px; border-bottom: 2px solid #cbd5e1; font-size: 10px; text-transform: uppercase; }
    td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
    .r { text-align: right; }
    .total-row td { border: none; font-size: 15px; font-weight: bold; padding-top: 16px; }
    .footer { margin-top: 48px; font-size: 10px; color: #94a3b8; text-align: center; }
    .header td { border: none; padding: 0; }
  </style>
</head>
<body>
  <table class="header">
    <tr>
      <td>
        <h1>INVOICE</h1>
        <p>Intelligent ERP Demo Company</p>
      </td>
      <td class="meta">
        <strong>{{ $invoice->number }}</strong><br>
        Issued: {{ $invoice->issued_at?->format('Y-m-d') }}<br>
        Sale: {{ $sale->number }} ({{ $sale->sale_date->format('Y-m-d') }})
      </td>
    </tr>
  </table>

  <div class="parties">
    <p class="label">Billed to</p>
    <strong>{{ $sale->customer->name }}</strong><br>
    @if ($sale->customer->address) {{ $sale->customer->address }}<br> @endif
    @if ($sale->customer->email) {{ $sale->customer->email }}<br> @endif
    @if ($sale->customer->phone) {{ $sale->customer->phone }} @endif
  </div>

  <table>
    <thead>
      <tr><th>SKU</th><th>Product</th><th class="r">Qty</th><th class="r">Unit price</th><th class="r">Subtotal</th></tr>
    </thead>
    <tbody>
      @foreach ($sale->lines as $line)
      <tr>
        <td>{{ $line->product->sku }}</td>
        <td>{{ $line->product->name }}</td>
        <td class="r">{{ $line->quantity }}</td>
        <td class="r">{{ number_format($line->unit_price, 2) }}</td>
        <td class="r">{{ number_format($line->quantity * $line->unit_price, 2) }}</td>
      </tr>
      @endforeach
      <tr class="total-row">
        <td colspan="4" class="r">Total due</td>
        <td class="r">{{ number_format($sale->total_amount, 2) }}</td>
      </tr>
    </tbody>
  </table>

  <p class="footer">Generated by Intelligent ERP — {{ $invoice->number }}</p>
</body>
</html>
